quarkus:
  devservices:
    enabled: false
  datasource:
    datasource1:
      db-kind: postgresql
      username: user
      password: pwd
      jdbc:
        url: jdbc:postgresql://localhost:5432/datasource1
    datasource2:
      db-kind: postgresql
      username: user
      password: pwd
      jdbc:
        url: jdbc:postgresql://localhost:5432/datasource1
  hibernate-orm:
    datasource1:
      datasource: "datasource1"
      packages: org.example.entity.datasource1
      database:
        generation: drop-and-create
    datasource2:
      datasource: "datasource2"
      packages: org.example.entity.datasource2
      database:
        generation: drop-and-create